# Simulation parameters for PLR ATE Coverage

simulation_parameters:
  repetitions: 10
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [500] # Sample size
  dim_x: [20] # Number of covariates
  dim_z: [1] # Number of instruments

# Define reusable learner configurations
learner_definitions:
  lasso: &lasso
    name: "LassoCV"

  rf: &rf
    name: "RF Regr."
    params:
      n_estimators: 200
      max_features: 10
      max_depth: 5
      min_samples_leaf: 20

dml_parameters:
  # ML methods for ml_g and ml_m
  learners:
    - ml_g: *lasso
      ml_m: *lasso
      ml_r: *lasso
    - ml_g: *rf
      ml_m: *rf
      ml_r: *rf
    - ml_g: *lasso
      ml_m: *rf
      ml_r: *rf
    - ml_g: *rf
      ml_m: *lasso
      ml_r: *rf
    - ml_g: *rf
      ml_m: *rf
      ml_r: *lasso
    - ml_g: *lasso
      ml_m: *lasso
      ml_r: *rf
    - ml_g: *rf
      ml_m: *lasso
      ml_r: *lasso
    - ml_g: *lasso
      ml_m: *rf
      ml_r: *lasso

  score: ["partialling out", "IV-type"]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
