# Simulation parameters for PLR ATE Coverage

simulation_parameters:
  repetitions: 1000
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [500] # Sample size
  dim_x: [20] # Number of covariates

dml_parameters:
  # ML methods for ml_g and ml_m
  learners:
    - ml_g: ["Lasso"]
      ml_m: ["Lasso"]
    - ml_g: ["Random Forest"]
      ml_m: ["Random Forest"]
    - ml_g: ["Lasso"]
      ml_m: ["Random Forest"]
    - ml_g: ["Random Forest"]
      ml_m: ["Lasso"]
    - ml_g: ["LGBM"]
      ml_m: ["LGBM"]
    - ml_g: ["LGBM"]
      ml_m: ["Lasso"]

  score: ["partialling out", "IV-type"]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels