# Simulation parameters for PLR ATE Sensitivity Coverage

simulation_parameters:
  repetitions: 1000
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [1000] # Sample size

# Define reusable learner configurations
learner_definitions:
  lasso: &lasso
    name: "LassoCV"

  rf: &rf
    name: "RF Regr."
    params:
      n_estimators: 200
      max_features: 10
      max_depth: 5
      min_samples_leaf: 2

  lgbm: &lgbm
    name: "LGBM Regr."
    params:
      n_estimators: 500
      learning_rate: 0.05
      min_child_samples: 5

dml_parameters:
  learners:
    - ml_g: *lasso
      ml_m: *lasso
    - ml_g: *rf
      ml_m: *rf
    - ml_g: *lasso
      ml_m: *rf
    - ml_g: *rf
      ml_m: *lasso
    - ml_g: *lgbm
      ml_m: *lgbm
    - ml_g: *lgbm
      ml_m: *lasso
    - ml_g: *lasso
      ml_m: *lgbm

  score: ["partialling out", "IV-type"]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
