project:
  type: website

website:
  title: "DoubleML Coverage"
  favicon: _static/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "IRM"
        menu:
          - irm/irm.qmd
      - text: "PLM"
        menu:      
          - plm/plr.qmd
      - about.qmd
    right: 
      - icon: book
        href: https://docs.doubleml.org/stable/index.html
        aria-label: Documentation
      - icon: github
        href: https://github.com/DoubleML/doubleml-coverage
        aria-label: GitHub

format:
  html:
    theme: zephyr 
    css: styles.css
    toc: true
