project:
  type: website

website:
  favicon: logo.png
  title: "DoubleML Coverage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "IRM"
        menu:
          - irm/irm_ate.qmd
      - about.qmd
    right: 
      - icon: book
        href: https://docs.doubleml.org/stable/index.html
        aria-label: Documentation
      - icon: github
        href: https://github.com/DoubleML/doubleml-coverage
        aria-label: GitHub

format:
  html:
    theme:
      light: zephyr 
    css: styles.css
    toc: true
