---
title: "DiD for Panel Data over Multiple Periods"

jupyter: python3
---

```{python}
#| echo: false

import numpy as np
import pandas as pd
from itables import init_notebook_mode, show, options

init_notebook_mode(all_interactive=True)

def highlight_range(s, level=0.95, dist=0.05, props=''):
    color_grid = np.where((s >= level-dist) &
                          (s <= level+dist), props, '')
    return color_grid


def color_coverage(df, level):
    # color coverage column order is important
    styled_df = df.apply(
        highlight_range,
        level=level,
        dist=1.0,
        props='color:black;background-color:red',
        subset=["Coverage", "Uniform Coverage"])
    styled_df = styled_df.apply(
        highlight_range,
        level=level,
        dist=0.1,
        props='color:black;background-color:yellow',
        subset=["Coverage", "Uniform Coverage"])
    styled_df = styled_df.apply(
        highlight_range,
        level=level,
        dist=0.05,
        props='color:white;background-color:darkgreen',
        subset=["Coverage", "Uniform Coverage"])

    # set all coverage values to bold
    styled_df = styled_df.set_properties(
        **{'font-weight': 'bold'},
        subset=["Coverage", "Uniform Coverage"])
    return styled_df


def make_pretty(df, level, n_rep):
    styled_df = df.style.hide(axis="index")
    # Format only float columns
    float_cols = df.select_dtypes(include=['float']).columns
    styled_df = styled_df.format({col: "{:.3f}" for col in float_cols})

    # color coverage column order is important
    styled_df = color_coverage(styled_df, level)
    caption = f"Coverage for {level*100}%-Confidence Interval over {n_rep} Repetitions"

    return show(styled_df, caption=caption)
```

## ATTE Coverage

The simulations are based on the  the [make_did_CS2021](https://docs.doubleml.org/dev/api/generated/doubleml.did.datasets.make_did_CS2021.html)-DGP with $2000$ observations. Learners are both set to either boosting or a linear (logistic) model. Due to time constraints we only consider the following DGPs:

 - Type 1: Linear outcome model and treatment assignment
 - Type 4: Nonlinear outcome model and treatment assignment
 - Type 6: Randomized treatment assignment and nonlinear outcome model

The non-uniform results (coverage, ci length and bias) refer to averaged values over all $ATTs$ (point-wise confidende intervals).

::: {.callout-note title="Metadata"  collapse="true"}

```{python}
#| echo: false
metadata_file = '../../results/did/did_multi_metadata.csv'
metadata_df = pd.read_csv(metadata_file)
print(metadata_df.T.to_string(header=False))
```

:::

```{python}
#| echo: false

# set up data
df = pd.read_csv("../../results/did/did_multi_detailed.csv", index_col=None)

assert df["repetition"].nunique() == 1
n_rep = df["repetition"].unique()[0]

display_columns = ["Learner g", "Learner m", "DGP", "In-sample-norm.", "Bias", "CI Length", "Coverage", "Uniform CI Length", "Uniform Coverage"]
```

### Observational Score

```{python}
#| echo: false
score = "observational"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "observational"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```


### Experimental Score

The results are only valid for the DGP 6, as the experimental score assumes a randomized treatment assignment.

```{python}
#| echo: false
score = "experimental"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "experimental"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

## Aggregated Effects

These simulations test different types of aggregation, as described in [DiD User Guide](https://docs.doubleml.org/dev/guide/models.html#difference-in-differences-models-did).

The non-uniform results (coverage, ci length and bias) refer to averaged values over all $ATTs$ (point-wise confidende intervals).

### Group Effects

```{python}
#| echo: false

# set up data
df = pd.read_csv("../../results/did/did_multi_group.csv", index_col=None)

assert df["repetition"].nunique() == 1
n_rep = df["repetition"].unique()[0]

display_columns = ["Learner g", "Learner m", "DGP", "In-sample-norm.", "Bias", "CI Length", "Coverage", "Uniform CI Length", "Uniform Coverage"]
```

#### Observational Score

```{python}
#| echo: false
score = "observational"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "observational"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

#### Experimental Score

The results are only valid for the DGP 6, as the experimental score assumes a randomized treatment assignment.

```{python}
#| echo: false
score = "experimental"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "experimental"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

### Time Effects

```{python}
#| echo: false

# set up data
df = pd.read_csv("../../results/did/did_multi_time.csv", index_col=None)

assert df["repetition"].nunique() == 1
n_rep = df["repetition"].unique()[0]

display_columns = ["Learner g", "Learner m", "DGP", "In-sample-norm.", "Bias", "CI Length", "Coverage", "Uniform CI Length", "Uniform Coverage"]
```

#### Observational Score

```{python}
#| echo: false
score = "observational"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "observational"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

#### Experimental Score

The results are only valid for the DGP 6, as the experimental score assumes a randomized treatment assignment.

```{python}
#| echo: false
score = "experimental"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "experimental"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

### Event Study Aggregation

```{python}
#| echo: false

# set up data
df = pd.read_csv("../../results/did/did_multi_eventstudy.csv", index_col=None)

assert df["repetition"].nunique() == 1
n_rep = df["repetition"].unique()[0]

display_columns = ["Learner g", "Learner m", "DGP", "In-sample-norm.", "Bias", "CI Length", "Coverage", "Uniform CI Length", "Uniform Coverage"]
```

#### Observational Score

```{python}
#| echo: false
score = "observational"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "observational"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```

#### Experimental Score

The results are only valid for the DGP 6, as the experimental score assumes a randomized treatment assignment.


```{python}
#| echo: false
score = "experimental"
level = 0.95

df_ate_95 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_95, level, n_rep)
```

```{python}
#| echo: false
score = "experimental"
level = 0.9

df_ate_9 = df[(df['level'] == level) & (df["Score"] == score)][display_columns]
make_pretty(df_ate_9, level, n_rep)
```
