# Simulation parameters for sharp RDD Coverage

simulation_parameters:
  repetitions: 1000
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  n_obs: [1000] # Sample size
  fuzzy: [False]
  cutoff: [0.0]

# Define reusable learner configurations
learner_definitions:
  lgbmr: &lgbmr
    name: "LGBM Regr."
    params:
      n_estimators: 100
      learning_rate: 0.05

  global_linear: &global_linear
    name: "Global Linear"

  local_linear: &local_linear
    name: "Linear"

  stacked_reg: &stacked_reg
    name: "Stacked Regr."
    params:
      n_estimators: 100
      learning_rate: 0.05

dml_parameters:
  fs_specification: ["cutoff", "cutoff and score", "interacted cutoff and score"]

  learners:
    - ml_g: *lgbmr
    - ml_g: *global_linear
    - ml_g: *local_linear
    - ml_g: *stacked_reg


confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
