# Simulation parameters for DID Multi Coverage
repetitions: 2
max_runtime: 19800  # 5.5 hours in seconds
random_seed: 42
n_obs: 500  # Sample size

# Parameter grid for simulation
parameters:
  DGP: [1, 4, 6]  # Different DGP specifications
  score: 
    - observational  # Standard DML score
    - experimental   # Experimental score (no propensity estimation)
  
  in_sample_normalization: [true, false]
  
  # ML methods for outcome model
  learner_g:
    - ["Linear", "LinearRegression"]
  
  # ML methods for propensity score
  learner_m:
    - ["Linear", "LogisticRegression"]
  
  level: [0.95, 0.90]  # Confidence levels