# Simulation parameters for APO Coverage

simulation_parameters:
  repetitions: 1000
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  n_obs: [500] # Sample size
  n_levels: [2]
  linear: [True]

# Define reusable learner configurations
learner_definitions:
  linear: &linear
    name: "Linear"

  logit: &logit
    name: "Logistic"

  lgbmr: &lgbmr
    name: "LGBM Regr."
    params:
      n_estimators: 500
      learning_rate: 0.01
      min_child_samples: 10

  lgbmc: &lgbmc
    name: "LGBM Clas."
    params:
      n_estimators: 500
      learning_rate: 0.01
      min_child_samples: 10

dml_parameters:
  treatment_level: [0, 1, 2]
  trimming_threshold: [0.01]
  learners:
    - ml_g: *linear
      ml_m: *logit
    - ml_g: *lgbmr
      ml_m: *lgbmc
    - ml_g: *lgbmr
      ml_m: *logit
    - ml_g: *linear
      ml_m: *lgbmc


confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
