# Simulation parameters for IRM ATE Coverage

simulation_parameters:
  repetitions: 1000
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [0.5] # Treatment effect
  n_obs: [500] # Sample size
  dim_x: [20] # Number of covariates

# Define reusable learner configurations
learner_definitions:
  lasso: &lasso
    name: "LassoCV"

  logit: &logit
    name: "Logistic"

  rfr: &rfr
    name: "RF Regr."
    params:
      n_estimators: 200
      max_features: 20
      max_depth: 20
      min_samples_leaf: 2

  rfc: &rfc
    name: "RF Clas."
    params:
      n_estimators: 200
      max_features: 20
      max_depth: 20
      min_samples_leaf: 20

  lgbmr: &lgbmr
    name: "LGBM Regr."
    params:
      n_estimators: 500
      learning_rate: 0.01

  lgbmc: &lgbmc
    name: "LGBM Clas."
    params:
      n_estimators: 500
      learning_rate: 0.01

dml_parameters:
  learners:
    - ml_g: *lasso
      ml_m: *logit
    - ml_g: *rfr
      ml_m: *rfc
    - ml_g: *lasso
      ml_m: *rfc
    - ml_g: *rfr
      ml_m: *logit
    - ml_g: *lgbmr
      ml_m: *lgbmc
    - ml_g: *lgbmr
      ml_m: *logit
    - ml_g: *lasso
      ml_m: *lgbmc

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
