# Simulation parameters for IRM ATTE Coverage

simulation_parameters:
  repetitions: 10
  max_runtime: 19800 # 5.5 hours in seconds
  random_seed: 42
  n_jobs: -2

dgp_parameters:
  theta: [5.0] # Treatment effect
  n_obs: [5000] # Sample size
  trimming_threshold: [0.05] # Trimming threshold
  var_epsilon_y: [1.0] # Variance of outcome noise
  linear: [False]
  gamma_a: [0.151]
  beta_a: [0.582]

# Define reusable learner configurations
learner_definitions:
  linear: &linear
    name: "Linear"

  logit: &logit
    name: "Logistic"

  lgbmr: &lgbmr
    name: "LGBM Regr."
    params:
      n_estimators: 500
      learning_rate: 0.01
      min_child_samples: 10

  lgbmc: &lgbmc
    name: "LGBM Clas."
    params:
      n_estimators: 500
      learning_rate: 0.01
      min_child_samples: 10

dml_parameters:
  learners:
    - ml_g: *linear
      ml_m: *logit
    - ml_g: *lgbmr
      ml_m: *lgbmc
    - ml_g: *lgbmr
      ml_m: *logit
    - ml_g: *linear
      ml_m: *lgbmc

  trimming_threshold: [0.05]

confidence_parameters:
  level: [0.95, 0.90] # Confidence levels
