name: Run DID Scripts

on:
  workflow_dispatch:
    inputs:
        doubleml-py-branch:
          description: 'Branch in https://github.com/DoubleML/doubleml-for-py'
          required: true
          default: 'main'
  repository_dispatch:
    types: [run-did-scripts]

jobs:
  run-did-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          'scripts/did/did_pa_atte_coverage.py',
          'scripts/did/did_cs_atte_coverage.py',
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Determine branch name
      id: get-branch
      run: |
        if [ -n "${{ github.event.inputs.doubleml-py-branch }}" ]; then
          echo "BRANCH_NAME=${{ github.event.inputs.doubleml-py-branch }}" >> $GITHUB_ENV
        elif [ -n "${{ github.event.client_payload.doubleml_py_branch }}" ]; then
          echo "BRANCH_NAME=${{ github.event.client_payload.doubleml_py_branch }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=main" >> $GITHUB_ENV
        fi

    - name: Install DoubleML from correct branch
      run: |
        pip install git+https://github.com/DoubleML/doubleml-for-py@${{ env.BRANCH_NAME }}

    - name: Set up Git configuration
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Run scripts
      run: python ${{ matrix.script }}

    - name: Commit any existing changes
      run: |
        git add results/did
        git commit -m "Update results from script: ${{ matrix.script }}" || echo "No changed results to commit"

    - name: Pull the latest changes and push results
      run: |
        git pull --rebase origin ${{ github.ref_name }}
        git push origin ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}