
name: Quarto Publish Development Version

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./doc
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements-doc.txt

      - name: Render and Publish Development Version
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: ./doc
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PROFILE: dev
          QUARTO_PROJECT_OUTPUT_DIR: dev
