name: Run Scripts

on:
  workflow_dispatch:
    inputs:
      doubleml-py-branch:
        description: 'Branch in https://github.com/DoubleML/doubleml-for-py'
        required: true
        default: 'main'

jobs:
  trigger-did-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Run DID Scripts Workflow
        run: |
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"run-did-scripts\", \"client_payload\": { \
            \"doubleml_py_branch\": \"${{ github.event.inputs.doubleml-py-branch }}\", \
            \"target_branch\": \"${{ github.ref_name }}\"}}"

          echo "HTTP Status: $RESPONSE"
          cat response.txt